GET http://localhost:8080/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk5ODQ5MDUsImlhdCI6MTc0OTg5ODUwNSwiaXNzIjoiYmxvZyIsInJvbGVzIjpbInN1cGVyIGFkbWluIiwicGVudWxpcyIsImFkbWluIiwiZWRpdG9yIl0sInRva2VuX3ZlcnNpb24iOiI5NWI2OThkMS1lMzFjLTQyZTgtODIzZi1mMzRhOWZjZTE0YjkiLCJ1c2VyX2lkIjoiMDFKWFBLMFFZUDlRNDJLQzFaSjE4TVpXSjkifQ.CjQhkKghoQEQPwxETPPOppBEijyOMK9YoI9_lUnaQfA
###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "identifier": "superadmin1",
    "password": "superadmin1"
}

### Logout
POST http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk5ODQ5MDUsImlhdCI6MTc0OTg5ODUwNSwiaXNzIjoiYmxvZyIsInJvbGVzIjpbInN1cGVyIGFkbWluIiwicGVudWxpcyIsImFkbWluIiwiZWRpdG9yIl0sInRva2VuX3ZlcnNpb24iOiI5NWI2OThkMS1lMzFjLTQyZTgtODIzZi1mMzRhOWZjZTE0YjkiLCJ1c2VyX2lkIjoiMDFKWFBLMFFZUDlRNDJLQzFaSjE4TVpXSjkifQ.CjQhkKghoQEQPwxETPPOppBEijyOMK9YoI9_lUnaQfA
###

###
GET http://localhost:8080/api/nulis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk5ODQ5MDUsImlhdCI6MTc0OTg5ODUwNSwiaXNzIjoiYmxvZyIsInJvbGVzIjpbInN1cGVyIGFkbWluIiwicGVudWxpcyIsImFkbWluIiwiZWRpdG9yIl0sInRva2VuX3ZlcnNpb24iOiI5NWI2OThkMS1lMzFjLTQyZTgtODIzZi1mMzRhOWZjZTE0YjkiLCJ1c2VyX2lkIjoiMDFKWFBLMFFZUDlRNDJLQzFaSjE4TVpXSjkifQ.CjQhkKghoQEQPwxETPPOppBEijyOMK9YoI9_lUnaQfA
###

### Registrasi Tamu
POST http://localhost:8080/api/guest-register
Content-Type: application/json

{
    "full_name": "Tamu ke dua",
    "username": "tamu1",
    "email": "tamu1@gmail.com",
    "password": "tamu123"
}